### ISSUE TITLE
Practicing 2N-system

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#14]
After 2N it would be nice to practice
1: Smolen
2: Texas
3: Minor suit stayman
4: Stayman include puppet stayman

Slam hands after 2N

If you just use the TwoNotrump-script you get them over time, but often it is good to be able to select

**Comment by ADavidBailey** [comment]
Would leveling the responders hand be enough?

**Comment by ThorvaldAagaard** [comment]
It would be a help, but be aware that you level on HCP, and not distribution.

**Comment by ThorvaldAagaard** [comment]
I assumed you would add hcp > 4 and then try to level on different hcp ranges, but if you have these 4 options and try to level those I assume it could be OK.

For the robot it is very fine.

But I need some slammish single suited minor hands - and balanced for Gerber and Quantitative 4N

**Comment by ADavidBailey** [comment]
partscore = hcp(north)<5
game = hcp(north)>4 and hcp(north)<16
slam = hcp(north)>15

**Comment by ThorvaldAagaard** [comment]
Opposite 20-21 I would think slam could be possible with hcp + longest suit >=16 (or hcp + 2 longest suits >= 20)

**Comment by ADavidBailey** [comment]
I like the hcp+length idea.

how do you show a single-suit minor hand?

**Comment by ThorvaldAagaard** [comment]
In my system we use 4C directly to show slammish club, and 3S as minor stayman or slammish diamonds.
I also have 4S to show 6-5 in minors without slaminterest
![image](https://github.com/ADavidBailey/Practice-Bidding-Scenarios/assets/10560652/8451f844-cbd3-4de2-ab24-eaef6a6c3a0e)

**Comment by ADavidBailey** [comment]
I added 2N and Balanced, 2N and 2C, and 2N and Xfer.  These are leveled so that game/slam, Puppett/Smolen, or Texas/Minor transfers occur with about the same frequency.

**Comment by ADavidBailey** [comment]
Thorvald, do I need to do more?

**Comment by ThorvaldAagaard** [comment]
It is fine
