### ISSUE TITLE
minor2 definition is missing the spaces

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#31]
![image](https://github.com/ADavidBailey/Practice-Bidding-Scenarios/assets/10560652/fe1fa1bc-138a-40d1-87c4-f74aa0343f59)

4 times of the 8 it is defined

**Comment by ADavidBailey** [comment]
Fixed, I think.  (I'm not sure I found the MSS    =minor2 statements)  Maybe I just fixed them and then couldn't find them.  It's early here.

**Comment by ThorvaldAagaard** [comment]
Looks fine
