### ISSUE TITLE
General Discussion

### ISSUE THREAD

**Issue by ADavidBailey** [ADavidBailey/Practice-Bidding-Scenarios#32]
As I get more familiar with GitHub, it seems we need a place for general discussion of a project. Is 'Issues' a reasonable place to do that?

**Comment by ThorvaldAagaard** [comment]
On Github you also have discussions at the same level as issues - It seems you have used it last year.

https://github.com/ADavidBailey/Practice-Bidding-Scenarios/discussions/1

Issues should be more to fix issues :-)

**Comment by ADavidBailey** [comment]
Thanks.
