### ISSUE TITLE
Lebensohl and defense over their preempt

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#33]
As far as I can see you have not leveled the hands that double a weak 2 (or 3)

I would like to practice some hands where the doubler has 19+ HCP over any preempt

**Comment by ADavidBailey** [comment]
I've got so many...  

Lebensohl Over Weak 2
Opps Gambling 3N
Opps Multi 2D
Opps Preempt
Opps Weak Two
W2-X-XX

Please be more specific about scenarios.  And about leveling?  Just HCP for the Doubler?  What ranges?

I was vacationing with family for the last week.  I spent some idle time looking at various scenarios.  Many need attention.

**Comment by ThorvaldAagaard** [comment]
Looks fine.
My next step will be
Sync, and run extract.
Generate PBN-files
Test in BBA that the boards are the one I am looking for.

**Comment by ADavidBailey** [comment]
Wait until I move it from test folder.

**Comment by ThorvaldAagaard** [comment]
Yes, and if you generate the boards, I can take the PBN-file and read it directly into BBA :-)

**Comment by ADavidBailey** [comment]
It's installed as Dealer-WeXOppsWeak2.  You will need to extract...

**Comment by ADavidBailey** [comment]
Should I expand it to include opponents 3-level preempts?  4-level?

**Comment by ThorvaldAagaard** [comment]
Yes, that would be fine but I prefer individual scripts - I assume opening level is difficult to level

**Comment by ADavidBailey** [comment]
I just installed Dealer-WeXOppsPreempt.  I increased the HCP for South's X.  Here are the stats:

South X 14-15 : 28
South X 16-18 : 37.5
South X 19+   : 34.5
North Weak    : 35
North Invite  : 37.5
North Force   : 27.5
Generated 29041870 hands
Produced 600 hands
Initial random seed 1719428511
Time needed   51.410 sec

**Comment by ADavidBailey** [comment]
I also allowed doubler to have 5440 and 5431.

**Comment by ADavidBailey** [comment]
It looks like we missed lots of games, small slams, and grand slams after starting with a X or their Weak 2.

Statistics for /Users/adavidbailey/Practice-Bidding-Scenarios/BBA/We_X_Opps_Weak_2-EPBot.csv
   67  "We missed small slam"
  132  "Par was bid"
   52  "We missed best contract"
   89  "We missed game"
   15  "We missed grand slam"
   16  "We missed partial"
   41  "We overbid - undoubled"
    5  "We wrong-side contract"
   16  "We missed double"
   37  "They overbid - doubled"
   14  "They missed sacrifice"
    3  "They missed partial"
    4  "They missed double"
    4  "They overbid - undoubled"
    1  "They doubled making contract"
    2  "We doubled making contract"
    2  "We overbid - doubled"
_____
  500  TOTAL

       --- Par Scores ---
            count  vsPar avg
Grand Slam:   14     -13.29
Small Slam:   73     -10.34
Major Game:  105      -3.83
Minor Game:   10      -6.9
   NT Game:  153      -2.32
Part Score:  102      0.64
     Other:   43      -3.21
             500  TOTAL
