### ISSUE TITLE
They disturb over our 2C opening

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#35]
It is always diificult when the they preempt, but after out opening 2C it can be very difficult as we don't have any agreements.

Can you create a set for pratice?

An example
![image](https://github.com/user-attachments/assets/0d9761ce-5118-4f12-a79b-5c78ff25ea64)

**Comment by ADavidBailey** [comment]
Done.  I might need to tweek LHO's hand when they have clubs.  Let me know.

Look for Opps Bid Over GF 2C

**Comment by ThorvaldAagaard** [comment]
Thx

**Comment by ADavidBailey** [comment]
I tweaked it so if south suit is clubs, they'll have 7.  And, I added 73xx shape.

wC = clubs(west)>6    and top4(west,clubs)>2
wOvercalls = (wS or wH or wD or wC) and shape(west,any 75xx+any 74xx+any 73xx+any 65xx+any 64xx)
