### ISSUE TITLE
Reponders reverse

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#37]
This is a difficult one, as I am looking for responders reverse

So something like

1X -1Y
2X -2Z

Where z i higher than Y

I think there only are four possible sequences

**Comment by ADavidBailey** [comment]
Reverses is in the Minor/Major Sequences section.  Here's the chat:
→adb42 (Private): --- Reverses
→adb42 (Private): Reverses show 5+ cards in the suit opened and 4+ cards in the suit rebid. They show
→adb42 (Private): approximately the same strength as rebidding 2N -- about 17+ HCP. Possible reverses are...
→adb42 (Private): • 1♥ - 1N - 2♠
→adb42 (Private): • 1♦ - 1♠ - 2♥
→adb42 (Private): • 1♦ - 1N - 2♥/2♠
→adb42 (Private): • 1♣ - 1♥ - 2♦
→adb42 (Private): • 1♣ - 1♠ - 2♦/2♥
→adb42 (Private): • 1♣ - 1N - 2♦/2♥/1♠
→adb42 (Private): Reverses are NOT a convention. If you don't have the extra strength，don't reverse.

**Comment by ThorvaldAagaard** [comment]
Yes, that is openers reverse. I am looking for responders reverse

1♣ - 1♥
2♣ - 2♠

But also 
1X-2Y (Y less than X)
2X-2Z

**Comment by ADavidBailey** [comment]
I'll work on it.

**Comment by ADavidBailey** [comment]
Are these the uncontested sequences you want?

- 1!C - 1!D - 1N - 2!H or 2!S
- 1!C - 1!H - 1N - 2!S
- 1!C - 1!D - 2!C - 2!H or 2!S
- 1!D - 1!H - 1N - 2!S
- 1!D - 1!H - 2!D - 2!S

**Comment by ThorvaldAagaard** [comment]
Yes.
After 1N rebid, som might play New Minor Forcing or Two Way New Minor Foring, but I don't think that matters
(I do play 1Mi-1H-1N-2S as 4-4 and invitational, because 1N can have 4 spades)

Also add
1!C - 1!H - 2!C - 2!S

I think these also can be included
1!D-2!C-2!D- 2!H or 2!S
1!H-2!C/!D - 2!H - 2!S

**Comment by ADavidBailey** [comment]
Here's the code.

# Reverses by Resoponder

dealer south

##### Imported Script -- Predict Opening 1-Bid #####

Import,https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/-Script-Calm-Opponents
Import,https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/-Script-Predict-Opening-1-Bid
Import,https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/-Script-Predict-Response-to-1-Bid
Import,https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/-Script-Predict-Openers-Rebid


CDNHorS = CDN and shape(north,4x5x+x45x+4x6x+x46x)
CHNS    = CHN and shape(south,45xx+46xx)
CDCHorS = CDC and shape(north,4x5x+x45x+4x6x+x46x)
DHNS    = DHN and shape(south,45xx+46xx)
DHDS    = DHD and shape(south,45xx+46xx)

(CDNHorS or CHNS or CDCHorS or DHNS or DHDS) and hcp(south)>11 and hcp(south)<15 and hcp(north)>12 and calmOpps

I created the code to predict bidding sequences long ago.  I just had to add the 6 lines.

I'll probably have to tweak it.
I have not yet created files; so test it in PBS.  Let me know what you think.

**Comment by ThorvaldAagaard** [comment]
I first have to get Eedward to update BBA, as it is not bidding it correctly, but thx a lot

**Comment by ADavidBailey** [comment]
Some play 1D - 2C is GF some don't; so, I need to add it.

Doesn't everyone play 1H 2C/D as GF.  (Nevermind, I'll add it too.)

**Comment by ThorvaldAagaard** [comment]
When playing SAYC none of these are GF

**Comment by ADavidBailey** [comment]
As I was writing that, it occurred to me that not everyone plays 2/1.  Hence the, nevermind...

The pbn & lin files are done.

**Comment by ThorvaldAagaard** [comment]
Thank you
