### ISSUE TITLE
Responder has an invitational hand

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#43]
Perhaps they are included in other scenarios, but using BBA I have some trouble, when responder has an invitational hand (typical 10-12 HCP), and 3-card support to partner, or own 6-card suit.

Typical
1H-1S
1N 
Here we often play some checkback/New minor forcing sa that is probably overed
1H-1S
2Mi
Here I think both 3H and 3S is invitational (also 2N)
1Mi-1Ma
2Mi
Here 3Ma should be invitational (also 2N)

**Comment by ADavidBailey** [comment]
I'm having trouble understanding what you want.  I'm thinking after 3 bids where responder has 10-12 HCP.  And either a 6-card suit OR 3-card support.  I'm confused about the support.  Support for what?  Here are the possible 3-bid sequences:

CDH
CDS
CDN
DHS
DHN
DHC
HSN
HSC
HSD

What shapes in responder's hands are interesting to you?

**Comment by ADavidBailey** [comment]
I created a Fourth Bid Inviting Scenario.  I think this is what you want.  Let me know if I need to do more.

**Comment by ThorvaldAagaard** [comment]
Thank you
