### ISSUE TITLE
Opening 1N vs overcalling 1N

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#60]
When we open 1N we have practice deals for
Stayman
Texas
Smolen
Jacoby
Minor suit Stayman
Minor Suit Transfer
Gerber
(and probably more)

We have scenarios, when they double 1N or any of our artificial bids like Styaman or Jacoby and we also have some slammish scenarios.

Now when we overcall 1N it seems we have no scenarios, so I am looking for all of the above but after a natural overcall 1N.

**Comment by ADavidBailey** [comment]
They're on my list!

**Comment by ADavidBailey** [comment]
I've added We_Pvercall_NT_then
Jacoby
Texas
Stayman -- I configured this for Drop Dead, Crawling, or regular Stayman
Smolen

What can I do to get BBA to bid Drop Dead or Crawling?

**Comment by ThorvaldAagaard** [comment]
Hope that Edward find time to implement it, but I doubt it. He has a lot of open issues for BBA.

**Comment by ADavidBailey** [comment]
I could level it; but, for your purpose, it shouldn’t matter.

David Bailey
918-520-9700 mobile

**Comment by ADavidBailey** [comment]
I added MSS and MST.  FYI...
- MSS was bid 110 times.
- MST was bid 200 times.

**Comment by ADavidBailey** [comment]
> for your purpose, it shouldn’t matter.

I think I'm wrong!  You depend on both the deals AND the bidding to train Ben.  Right?

**Comment by ADavidBailey** [comment]
You might be interested in this.  A friend, uses an interesting system for 1N - 2S:
--- Ned’s 2 Spades\n\
6+ !C or 6+ !D or both (54) or better\n\
Opener responds 3!C if !C are longer than !D，otherwise 2N\n\
Responder can pass，bid 3!C or 3!D to play，or try for slam.\n\
3!H or 3!S show shortness with both minors -- at least 5/4\n\
3N = 22(54) w/16 HCP，4N w/17 HCP，5N w/20 HCP\n\
https://tinyurl.com/mtbmccfe\n\

**Comment by ThorvaldAagaard** [comment]
I am just looking for interesting deals.
Then I select how BEN should play by selecting the conventions in BBA, and let BBA bid all the hands.
So I am currently not looking for more advanced conventions, but Ned's 2S reminds me of how I play.

**Comment by ADavidBailey** [comment]
> and let BBA bid all the hands

So, you do care about how BBA bids the hands.

Ned's 2S was just an aside.

**Comment by ThorvaldAagaard** [comment]
Yes, that is why I have reported close to 1000 errors in BBA and still 700 open. Bridge is not easy :-)

**Comment by ADavidBailey** [comment]
I'm marking this one complete.  I've not yet heard from Edward about Gerber After NT.  If BBA will do it, I'll add it.

Please create a new issue for any others that occur to you.
