### ISSUE TITLE
Minor slams

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#62]
I am bidding minor slams and looked at:
https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/bba-summary/Minor_Slams.txt

and it would be interesting how many slams the set produced of the 500 deals.

It could be interesting both to know how many BBA bid, and how many could make Double Dummy.

Sum of actual contracts could be interessting for every set.

**Comment by ADavidBailey** [comment]
Searching the .pbn file in VSCode with regex:  Result..(12|13)  returns 256.

**Comment by ThorvaldAagaard** [comment]
As it is minorslams it is interesting to have the stats with suit also. I found a couple of slams in major

**Comment by ADavidBailey** [comment]
Try this:  Score.....(440|480|490|680|690|920|940|980|990|1010|1020|1090|1370|13901430|1440|1460|1520)

Or this:  Contract..[67]C.*\n.*\n.*\n.*\n.*\n.*\n.Score.....(920|940|1370|1390)

I'm sure there's a way to not have to repeat the .*\n all those times.  You could also include the negative scores.
