### ISSUE TITLE
Overcalling their Strong opening

### ISSUE THREAD

**Issue by ThorvaldAagaard** [ADavidBailey/Practice-Bidding-Scenarios#63]
I need some hands, where they open 2C and we overcall or preempt

**Comment by ADavidBailey** [comment]
I just installed, We_Overcall_Their_2C.  It includes simple overcalls w/6+ good suit and 12+hcp and preempts w/6+ good suit and 0-11 hcp.

**Comment by ThorvaldAagaard** [comment]
I don't think an opening hand is needed to overcalll 2Ma

**Comment by ADavidBailey** [comment]
What's the difference in a simple overcall and a jump-overcall?  Just judgement?

It's configured so that a 6-card suit an 12+ or a -7-8-9 card suit and 0+. How do you want that changed?

**Comment by ThorvaldAagaard** [comment]
As it is for pratice it is important that the players agree on which type of hands they bid over 2C.

So any 5+-5+ hand is a candidate. Any good 6-card should bid as they often have game - but of course depending on vulnerability.

So remote point limit on 6-card and add 2-suited hands with minimum 10 cards

**Comment by ADavidBailey** [comment]
Here's what I did...

https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/PBS/We_Overcall_Their_2C

Let me know if you think it needs adjustment.  BBA only bids 242 out of 500.
