### ISSUE TITLE
Error Generating Deal

### ISSUE THREAD

**Issue by noetic-coder** [ADavidBailey/Practice-Bidding-Scenarios#66]
Hi,

First of all, thank you so much for this great tool and for making it open source! 

I am running into several different bidding scenarios where I get the message "Error Generating Deal", right now I have verified the error with "Reverse by Opener" and "Reverse by Responder" but I recall seeing this in other scenarios as well.

Is this a known issue, or perhaps could this be something with my install? I have attempted resetting the data source and re-installing BBO Alert to no avail. I am attaching a couple of screenshots, please let me know if I can help troubleshoot this.

Thanks

<img width="414" alt="Screen Shot 2024-12-01 at 13 42 57" src="https://github.com/user-attachments/assets/715c641a-5555-4a86-bc53-369ff3a94f55">
<img width="448" alt="Screen Shot 2024-12-01 at 13 43 36" src="https://github.com/user-attachments/assets/378c4f8c-bb61-4150-9a42-e235e6167a5a">

**Comment by ADavidBailey** [comment]
Thank you very much.  I get the same error on Reverse by Opener.  I'll have it fixed soon.  Thank you for reporting this.

**Comment by ADavidBailey** [comment]
Reverse by opener and Reverse by Responder have been fixed.

BBOalert sees all backslashes a 'escape' characters.  and \n as a new line -- even when the \n is in a comment line.  So, I have to escape the escape by coding \\n.  Scream!!

**Comment by ADavidBailey** [comment]
I found and fixed a couple more.

**Comment by noetic-coder** [comment]
Wow, thank you for the lightning-quick fix! I have verified the fix on my end as well.

Crazy the whole backslash escaping the escape, remember fighting the same fight with in some gnarly perl code back in the day. The RegEx functionality sounds awesome, anywhere I can read up on what you have cooking?

**Comment by noetic-coder** [comment]
Happy to close this issue and reopen if I find more scenarios by the way

**Comment by ADavidBailey** [comment]
Long, long, ago... I created a Document:  [Practice Bidding Scenarios - Under the Covers](https://github.com/ADavidBailey/Practice-Bidding-Scenarios/blob/main/Documents/Practice%20Bidding%20Scenarios%20-%20Under%20the%20Covers.md)

It's horribly out of date.  Remind me to bring it up to date.

**Comment by ADavidBailey** [comment]
Thanks again.
